Store/get hiddmode in/from bm->Planes[7]. Don't try to query it from screen bitmap obj, because of the (ugly/stupid) case when gfx driver does not implement screen switching but it is emulated by graphics.library (in which case a screen can either "point" to an offscreen bitmap obj or the framebuffer bitmap obj depending on whether screen is visible/frontmost one or not).
git-svn-id: https://svn.aros.org:8080/svn/aros/trunk/AROS@24256 fb15a70f-31f2-0310-bbcc-cdcc74a49acc