Added isspace to stubs list. Needed to #include <ctype.h> in arosc_functable.c to avoid a compilation error.
git-svn-id: https://svn.aros.org:8080/svn/aros/trunk/AROS@21593 fb15a70f-31f2-0310-bbcc-cdcc74a49acc