__IDSTRING and/or __RCSID may have been defined in the hosts headers, so protect them against multiple definitions.
git-svn-id: https://svn.aros.org:8080/svn/aros/trunk/AROS@16398 fb15a70f-31f2-0310-bbcc-cdcc74a49acc